//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THOITIET.Properties {
    using System;
    
    
    /// <summary>
    ///   Lớp tài nguyên kiểu mạnh, dùng tra cứu chuỗi/tài nguyên bản địa hóa.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaiNguyen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaiNguyen() {
        }
        
        /// <summary>
        ///   Trả về thể hiện ResourceManager được lưu trong bộ nhớ đệm của lớp.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("THOITIET.Properties.Resources", typeof(TaiNguyen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Ghi đè thuộc tính CurrentUICulture của luồng hiện tại cho mọi
        ///   tra cứu tài nguyên sử dụng lớp tài nguyên kiểu mạnh này.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Truy xuất tài nguyên bản địa hóa kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap giong_bao_dem {
            get {
                object obj = ResourceManager.GetObject("giong_bao_dem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Truy xuất tài nguyên bản địa hóa kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap may_day_dem {
            get {
                object obj = ResourceManager.GetObject("may_day_dem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Truy xuất tài nguyên bản địa hóa kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nen_troi_quang {
            get {
                object obj = ResourceManager.GetObject("nen_troi_quang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
