//------------------------------------------------------------------------------
// <auto-generated>
//     Mã này được tạo bởi một công cụ.
//     Phiên bản Runtime:4.0.30319.42000
//
//     Thay đổi tệp này có thể gây ra hành vi không chính xác và sẽ bị mất nếu
//     mã được tạo lại.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THOITIET.Properties {
    using System;
    
    
    /// <summary>
    ///   Lớp tài nguyên được gõ mạnh, để tra cứu chuỗi được bản địa hóa, v.v.
    /// </summary>
    // Lớp này được tạo tự động bởi StronglyTypedResourceBuilder
    // thông qua một công cụ như ResGen hoặc Visual Studio.
    // Để thêm hoặc xóa thành viên, hãy chỉnh sửa tệp .ResX của bạn rồi chạy lại ResGen
    // với tùy chọn /str, hoặc tạo lại dự án VS của bạn.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("THOITIET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap giong_bao_dem {
            get {
                object obj = ResourceManager.GetObject("giong_bao_dem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap may_day_dem {
            get {
                object obj = ResourceManager.GetObject("may_day_dem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nen_troi_quang {
            get {
                object obj = ResourceManager.GetObject("nen_troi_quang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
